# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='codigo_postal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
