# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0003_auto_20151211_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='codigo_postal',
            field=models.IntegerField(),
        ),
    ]
