# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0005_auto_20151211_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
