# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0007_auto_20151218_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrado',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='myfolder/'),
        ),
    ]
